# Generated by Django 5.0.2 on 2025-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationtrack',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='meditationtrack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meditation_images/'),
        ),
        migrations.AddField(
            model_name='meditationtrack',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
