# Generated by Django 5.0.2 on 2025-02-12 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_course_event_group_topcontent_workshop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='meditationtrack',
            options={'verbose_name': 'Meditation Track', 'verbose_name_plural': 'Meditation Tracks'},
        ),
        migrations.AlterModelOptions(
            name='topcontent',
            options={'verbose_name': 'Top Content', 'verbose_name_plural': 'Top Content'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshops'},
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.IntegerField(help_text='Duration in weeks', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration in weeks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Members Count'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='group',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='audio_file',
            field=models.FileField(help_text='Upload MP3 or WAV file', upload_to='meditation_tracks/', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meditationtrack',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='max_participants',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Participants'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('birth_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Birth Year')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
