# Generated by Django 5.0.2 on 2025-02-12 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0004_alter_course_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('tracks', 'Tracks Page'), ('courses', 'Courses Page'), ('workshops', 'Workshops Page'), ('groups', 'Groups Page'), ('events', 'Events Page')], max_length=20, unique=True, verbose_name='Page')),
                ('theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme')], default='light', max_length=10, verbose_name='Theme')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='page_backgrounds/', verbose_name='Background Image')),
                ('background_video', models.FileField(blank=True, help_text='Upload MP4 or WebM file', null=True, upload_to='page_backgrounds/', verbose_name='Background Video')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='HEX color code (e.g. #FFFFFF)', max_length=7, verbose_name='Background Color')),
                ('background_opacity', models.DecimalField(decimal_places=2, default=1.0, help_text='Value between 0 and 1', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Background Opacity')),
            ],
            options={
                'verbose_name': 'Page Background',
                'verbose_name_plural': 'Page Backgrounds',
            },
        ),
    ]
