# Generated by Django 5.0.2 on 2025-02-12 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0005_pagebackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebackground',
            name='background_opacity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Background Opacity'),
        ),
        migrations.AlterUniqueTogether(
            name='pagebackground',
            unique_together={('page', 'theme')},
        ),
    ]
