# Generated by Django 5.0.2 on 2025-02-12 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0006_alter_pagebackground_background_opacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMeditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='meditation.meditationtrack', verbose_name='Meditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_meditations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite Meditation',
                'verbose_name_plural': 'Favorite Meditations',
                'unique_together': {('user', 'meditation')},
            },
        ),
    ]
