# Generated by Django 5.0.2 on 2025-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0007_favoritemeditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebackground',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('tracks', 'Tracks Page'), ('courses', 'Courses Page'), ('workshops', 'Workshops Page'), ('groups', 'Groups Page'), ('events', 'Events Page'), ('favorites', 'Favorites Page')], max_length=20, unique=True, verbose_name='Page'),
        ),
    ]
