# Generated by Django 4.2.9 on 2025-02-17 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebackground',
            name='background_opacity',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Value between 0 and 1', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Background Opacity'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('tracks', 'Tracks Page'), ('courses', 'Courses Page'), ('workshops', 'Workshops Page'), ('groups', 'Groups Page'), ('events', 'Events Page'), ('favorites', 'Favorites Page')], max_length=20, verbose_name='Page'),
        ),
    ]
