# Generated by Django 5.0.2 on 2025-02-17 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0010_alter_pagebackground_background_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebackground',
            name='background_opacity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Background Opacity'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('tracks', 'Tracks Page'), ('courses', 'Courses Page'), ('workshops', 'Workshops Page'), ('groups', 'Groups Page'), ('events', 'Events Page'), ('favorites', 'Favorites Page')], max_length=20, unique=True, verbose_name='Page'),
        ),
    ]
